/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.budthapa.jts.helpers;

import com.budthapa.jts.view.job.JobFrame;
import java.awt.Color;

/**
 *
 * @author Buddhi Bal Thapa, budthapa@gmail.com
 */
public class ErrorPanel extends javax.swing.JPanel {
    private String errorMessage="";
    private String errorMessageColor="";
    /**
     * Creates new form ErrorPanel
     */
    public ErrorPanel() {
        initComponents();
        setSize(300, 30);
        setLocation(475, 40);
        setVisible(true);
        System.out.println("error panel");
    }

    protected void setErrorMessageAndColor(String errorMessage, String errorMessageColor) {
        
        new JobFrame().addErrorPanel();
        
        System.out.println("setting error msg and color");
        System.out.println("e msg "+errorMessage+" e color : "+errorMessageColor);

        this.lblMessage.setText(this.errorMessage);
//        lblMessage.setVisible(true);
        if (errorMessageColor.equals("RED")) {
            System.out.println("color ");
            this.lblMessage.setForeground(Color.RED);
        } else {
            this.lblMessage.setForeground(Color.GREEN);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();

        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMessage.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
