/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.budthapa.jts.view.user;

import com.budthapa.jts.business.UserBL;
import com.budthapa.jts.model.UserBean;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author budthapa
 */
public class ViewUser extends javax.swing.JInternalFrame {

    private UserBL user;
    private UserBean userBean;
    public static DefaultTableModel table;

    /**
     * Creates new form ViewUser
     */
    public ViewUser() {
        initComponents();
        setVisible(true);
        user = new UserBL();
        userBean = new UserBean();
        //bring table data from user
        initialiseTableAndFillWithData();
        
        //set ViewUser is already opened flag
        user.isViewUserClassOpen=true;
    }

    public void refreshTable(){
        initialiseTableAndFillWithData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewUsersTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("View list of Users");

        viewUsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewUsersTable.setToolTipText("Double Click to Edit or Delete this row.");
        viewUsersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewUsersTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(viewUsersTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialiseTableAndFillWithData() {
        //initialise table and set editable to false
        table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };

        List<UserBean> userList = user.getUserList();
        //column name is compulsary, if not added, added rows will not be displayed
        table.addColumn("S.No");
        table.addColumn("User Name");
        table.addColumn("User Position");
        table.addColumn("User Email");
        table.addColumn("Contact Number");
        table.addColumn("Address");

        for (UserBean userList1 : userList) {
            //create dynamic row
            Object[] rowData = {userList1.getUserId(), userList1.getUsername(), userList1.getUserPosition(), userList1.getUserEmail(), userList1.getUserContactNumber(), userList1.getUserAddress()};
            table.addRow(rowData);
        }
        viewUsersTable.setModel(table);

    }

    private void viewUsersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersTableMouseClicked

        int id;
        String name;
        String position;
        String email;
        String contactNumber;
        String address;

        //if user click twice in a row
        if (evt.getClickCount() == 2) {
            JTable table = (JTable) evt.getSource();
            int selectedRow = table.getSelectedRow();

            //get the items from the row starting from column index 0 to column max size;
            int counter=0;
            id = (int) table.getValueAt(selectedRow, counter);
            name = (String) table.getValueAt(selectedRow, ++counter);
            position = (String) table.getValueAt(selectedRow, ++counter);
            email = (String) table.getValueAt(selectedRow, ++counter);
            contactNumber = (String) table.getValueAt(selectedRow, ++counter);
            address = (String) table.getValueAt(selectedRow, ++counter);

            //populate the view new user with these new values
            UserBean ub =new UserBean(id, name, "","",position, email, contactNumber, address);

            //open dialog to edit or delete the user;
            EditUser editUser = new EditUser();
            UserFrame frame = new UserFrame();
            frame.getFrame();
            frame.setVisible(true);
            editUser.add(frame);

            //set button text dynamically
            //set button text to 'update' while accessing from this class
            String buttonText = "Update";
            frame.setButtonText(buttonText);

            frame.setValuesToEdit(ub);

            editUser.rowIdToDelete = selectedRow;
        }
    }//GEN-LAST:event_viewUsersTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable viewUsersTable;
    // End of variables declaration//GEN-END:variables

}
