/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.budthapa.jts.view.media;

import com.budthapa.jts.business.MediaHouseBL;
import com.budthapa.jts.model.MediaHouseBean;
import com.budthapa.jts.view.main.LoginPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author budthapa
 */
public class EditMediaHouse extends javax.swing.JDialog {

    static int mediaIdToDelete;
    static int rowIdToDelete;

    /**
     * Creates new form EditClient
     */
    public EditMediaHouse() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);

        //hide delete button from user
        if(!LoginPanel.loggedInUser.equals("admin")){
            btnDeleteMediaHouse.setVisible(false);
        }
        //dynamic update button is added from ViewMediaHouse class
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        btnDeleteMediaHouse = new javax.swing.JButton();

        setTitle("Edit or Delete Client");

        btnDeleteMediaHouse.setText("Delete");
        btnDeleteMediaHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMediaHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeleteMediaHouse)
                .addContainerGap(737, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteMediaHouse)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 503, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMediaHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMediaHouseActionPerformed
        //first show the confirm dialog box
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want to delete this Client?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {

            //delete the selected row
            //get the user id from MediaHouseBean where the data is set from ViewMediaHouse when double clicking the row
            boolean isMediaDeleted = MediaHouseBL.deleteMediaHouse(mediaIdToDelete);
            if (isMediaDeleted) {
                setVisible(false);
                //need to update the table view automatically
                //pass isMediaDeleted to ViewMediaHouse class so that table gets referesed automatically
                ViewMediaHouse.table.fireTableDataChanged();
                ViewMediaHouse.table.removeRow(rowIdToDelete);
            }
        }
    }//GEN-LAST:event_btnDeleteMediaHouseActionPerformed

    public static void refreshTableAfterUpdate(MediaHouseBean media) {
        //reload the ViewMediaHouse
        //need to update the table view automatically
        
        Object[] rowData = {
            media.getMediaId(), media.getMediaName(), media.getMediaEmail(), media.getMediaContactPerson(), media.getMediaContactNumber(), media.getMediaFax(), media.isNewspaper(), media.isTelevision(), media.isRadio(), media.isOnline(), media.isMagazine(), media.getOtherMedia(),media.getMediaAddress()
        };
        ViewMediaHouse.table.fireTableDataChanged();
        ViewMediaHouse.table.removeRow(rowIdToDelete);
        ViewMediaHouse.table.insertRow(rowIdToDelete, rowData);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteMediaHouse;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
