/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.budthapa.jts.view.media;

import com.budthapa.jts.business.MediaHouseBL;
import com.budthapa.jts.model.MediaHouseBean;
import javax.swing.JInternalFrame;

/**
 *
 * @author budthapa
 */
public class MediaHouseFrame extends javax.swing.JInternalFrame {

    public String buttonText;
    MediaHouseBean media;
    private String otherMedia = "";

    /**
     * Creates new form ClientFrame
     */
    public MediaHouseFrame() {
        initComponents();
        //hide titlebar
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
        this.buttonText = "";
        mediaHouseId.setVisible(false);
    }

    public JInternalFrame getFrame() {
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        clientLeftPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        editPanel1 = new javax.swing.JPanel();
        mediaHouseName = new javax.swing.JTextField();
        mediaHouseEmail = new javax.swing.JTextField();
        mediaHouseContactPerson = new javax.swing.JTextField();
        mediaHouseContactNumber = new javax.swing.JTextField();
        mediaHouseFaxNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mediaHouseAddress = new javax.swing.JTextArea();
        lblErrorMessage = new javax.swing.JLabel();
        btnSaveMediaHouse = new javax.swing.JButton();
        mediaHouseId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        chckbxNewspaper = new javax.swing.JCheckBox();
        chckbxTelevision = new javax.swing.JCheckBox();
        chckbxFmRadio = new javax.swing.JCheckBox();
        chckbxOnline = new javax.swing.JCheckBox();
        chckbxMagazine = new javax.swing.JCheckBox();
        chckbxOthers = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        otherMediaHouseType = new javax.swing.JTextField();

        setBorder(null);

        clientLeftPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel29.setText("Media House Name");

        jLabel30.setText("Media Type");

        jLabel31.setText("Email");

        jLabel32.setText("Contact No.");

        jLabel33.setText("Fax");

        jLabel34.setText("Contact Person");

        jLabel35.setText("Address");

        javax.swing.GroupLayout clientLeftPanel4Layout = new javax.swing.GroupLayout(clientLeftPanel4);
        clientLeftPanel4.setLayout(clientLeftPanel4Layout);
        clientLeftPanel4Layout.setHorizontalGroup(
            clientLeftPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientLeftPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientLeftPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientLeftPanel4Layout.setVerticalGroup(
            clientLeftPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientLeftPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addGap(115, 115, 115)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(25, 25, 25)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mediaHouseFaxNumber.setText("000000");

        mediaHouseAddress.setColumns(20);
        mediaHouseAddress.setRows(5);
        jScrollPane1.setViewportView(mediaHouseAddress);

        lblErrorMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSaveMediaHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMediaHouseActionPerformed(evt);
            }
        });

        chckbxNewspaper.setText("Newspaper");

        chckbxTelevision.setText("Television");

        chckbxFmRadio.setText("FM / Radio");

        chckbxOnline.setText("Online");

        chckbxMagazine.setText("Magazine");

        chckbxOthers.setText("Other");
        chckbxOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxOthersActionPerformed(evt);
            }
        });

        jLabel1.setText("If others, Please specify...");

        otherMediaHouseType.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(otherMediaHouseType)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chckbxNewspaper)
                            .addComponent(chckbxOnline))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chckbxMagazine)
                            .addComponent(chckbxTelevision))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chckbxOthers)
                            .addComponent(chckbxFmRadio))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chckbxNewspaper)
                    .addComponent(chckbxTelevision)
                    .addComponent(chckbxFmRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chckbxOnline)
                    .addComponent(chckbxMagazine)
                    .addComponent(chckbxOthers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otherMediaHouseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editPanel1Layout = new javax.swing.GroupLayout(editPanel1);
        editPanel1.setLayout(editPanel1Layout);
        editPanel1Layout.setHorizontalGroup(
            editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mediaHouseContactPerson)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediaHouseName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediaHouseContactNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediaHouseFaxNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mediaHouseEmail, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanel1Layout.createSequentialGroup()
                        .addComponent(mediaHouseId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304))
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(editPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnSaveMediaHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editPanel1Layout.setVerticalGroup(
            editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediaHouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediaHouseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(mediaHouseEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mediaHouseContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mediaHouseContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mediaHouseFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnSaveMediaHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientLeftPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientLeftPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(editPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMediaHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMediaHouseActionPerformed
        this.buttonText = btnSaveMediaHouse.getText();
        if (btnSaveMediaHouse.getText().equals("Save")) {
            media = new MediaHouseBean(0, mediaHouseName.getText().trim(), mediaHouseEmail.getText(), mediaHouseContactPerson.getText(), mediaHouseContactNumber.getText(), mediaHouseFaxNumber.getText(), mediaHouseAddress.getText(), chckbxNewspaper.isSelected(), chckbxTelevision.isSelected(), chckbxFmRadio.isSelected(), chckbxOnline.isSelected(), chckbxMagazine.isSelected(), chckbxOthers.isSelected(), otherMediaHouseType.getText());
        } else {
            media = new MediaHouseBean(Integer.parseInt(mediaHouseId.getText()), mediaHouseName.getText(), mediaHouseEmail.getText(), mediaHouseContactPerson.getText(), mediaHouseContactNumber.getText(), mediaHouseFaxNumber.getText(), mediaHouseAddress.getText(), chckbxNewspaper.isSelected(), chckbxTelevision.isSelected(), chckbxFmRadio.isSelected(), chckbxOnline.isSelected(), chckbxMagazine.isSelected(), chckbxOthers.isSelected(), otherMediaHouseType.getText());
        }
        MediaHouseBL.getButtonText(buttonText);
        MediaHouseBL.passMediaHouseObject(media);
    }//GEN-LAST:event_btnSaveMediaHouseActionPerformed

    private void chckbxOthersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxOthersActionPerformed
        boolean other = chckbxOthers.isSelected();
        if (other) {
            otherMediaHouseType.setEditable(true);
//            otherMedia = otherMediaHouseType.getText();
        } else {
            otherMediaHouseType.setEditable(false);
            otherMediaHouseType.setText("");
        }
    }//GEN-LAST:event_chckbxOthersActionPerformed

    void setButtonText(String buttonText) {
        btnSaveMediaHouse.setText(buttonText);
    }

    void setValuesToEdit(MediaHouseBean mhb) {
        EditMediaHouse.mediaIdToDelete = mhb.getMediaId();
        mediaHouseId.setText(String.valueOf(mhb.getMediaId()));
        mediaHouseName.setText(mhb.getMediaName());
        mediaHouseEmail.setText(mhb.getMediaEmail());
        mediaHouseContactPerson.setText(mhb.getMediaContactPerson());
        mediaHouseContactNumber.setText(mhb.getMediaContactNumber());
        mediaHouseFaxNumber.setText(mhb.getMediaFax());
        chckbxNewspaper.setSelected(mhb.isNewspaper());
        chckbxTelevision.setSelected(mhb.isTelevision());
        chckbxFmRadio.setSelected(mhb.isRadio());
        chckbxOnline.setSelected(mhb.isOnline());
        chckbxMagazine.setSelected(mhb.isMagazine());
        chckbxOthers.setSelected(mhb.isOther());
        otherMediaHouseType.setText(mhb.getOtherMedia());
        mediaHouseAddress.setText(mhb.getMediaAddress());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveMediaHouse;
    private javax.swing.JCheckBox chckbxFmRadio;
    private javax.swing.JCheckBox chckbxMagazine;
    private javax.swing.JCheckBox chckbxNewspaper;
    private javax.swing.JCheckBox chckbxOnline;
    private javax.swing.JCheckBox chckbxOthers;
    private javax.swing.JCheckBox chckbxTelevision;
    private javax.swing.JPanel clientLeftPanel4;
    private javax.swing.JPanel editPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblErrorMessage;
    private javax.swing.JTextArea mediaHouseAddress;
    private javax.swing.JTextField mediaHouseContactNumber;
    private javax.swing.JTextField mediaHouseContactPerson;
    private javax.swing.JTextField mediaHouseEmail;
    private javax.swing.JTextField mediaHouseFaxNumber;
    private javax.swing.JTextField mediaHouseId;
    private javax.swing.JTextField mediaHouseName;
    private javax.swing.JTextField otherMediaHouseType;
    // End of variables declaration//GEN-END:variables

}
