package com.budthapa.jts.view.job;

import com.budthapa.jts.business.JobBL;
import com.budthapa.jts.model.JobBean;
import com.budthapa.jts.view.main.LoginPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author budthapa
 */
public class EditJob extends javax.swing.JDialog {

    static int jobIdToDelete;
    static int rowIdToDelete;
    private static String jobCompleted;

    /**
     * Creates new form EditClient
     */
    public EditJob() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        
        //hide delete button from user
        if (!new LoginPanel().isUserAdmin()) {
            btnDeleteJob.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        btnDeleteJob = new javax.swing.JButton();

        setTitle("Update Job");

        headerPanel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnDeleteJob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteJob.setForeground(new java.awt.Color(255, 0, 0));
        btnDeleteJob.setText("Delete");
        btnDeleteJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteJobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(839, Short.MAX_VALUE)
                .addComponent(btnDeleteJob, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(btnDeleteJob, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 599, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteJobActionPerformed
        //first show the confirm dialog box
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you really want to delete this Job?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {

            //delete the selected row
            //get the user id from JobHouseBean where the data is set from ViewJob when double clicking the row
            boolean isJobDeleted = JobBL.deleteJob(jobIdToDelete);
            if (isJobDeleted) {
                setVisible(false);
                //need to update the table view automatically
                //pass isJobDeleted to ViewJob class so that table gets referesed automatically
                ViewJob.table.fireTableDataChanged();
                ViewJob.table.removeRow(rowIdToDelete);
            }
        }
    }//GEN-LAST:event_btnDeleteJobActionPerformed

    public static void refreshTableAfterUpdate(JobBean job) {
        //reload the ViewJob
        //need to update the table view automatically
                        System.out.println("isJobCompleted "+job.isJobCompleted());

        if (job.isJobCompleted()) {
            jobCompleted = "Completed";
        } else {
            jobCompleted = "On Progress";
        }
        Object[] rowData = {
            job.getJobId(), job.getJobName(), job.getAssigneeName(), job.isDesignTypeBlackAndWhite(),
            job.isDesignTypeColor(), job.getSizeColumn(), job.getSizeCm(), job.getClientName(),
            job.getMediaHouseName(), job.isLanguageNepali(), job.isLanguageEnglish(), job.getPosition(),
            job.getPublicationDays(), job.getJobContents(), job.getDueDate(),jobCompleted};
        ViewJob.table.fireTableDataChanged();
        ViewJob.table.removeRow(rowIdToDelete);
        ViewJob.table.insertRow(rowIdToDelete, rowData);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnDeleteJob;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
