/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.budthapa.jts.view.job;

import com.budthapa.jts.business.JobBL;
import com.budthapa.jts.business.UserBL;
import com.budthapa.jts.helpers.DateAndCalender;
import com.budthapa.jts.helpers.ErrorMessages;
import com.budthapa.jts.helpers.ErrorPanel;
import com.budthapa.jts.helpers.PrintPosition;
import com.budthapa.jts.model.JobBean;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author budthapa
 */
public class JobFrame extends javax.swing.JInternalFrame {

    public String buttonText;
    JobBean job;
    private String otherJob = "";
    JobBL jobBl;
    UserBL userBl;
    DefaultComboBoxModel combo;

    /**
     * Creates new form ClientFrame
     */
    public JobFrame() {
        initComponents();
        //hide titlebar
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
        this.buttonText = "";
        jobId.setVisible(false);
        /**
         * **************add user to combo box starts**********************
         */
        //get data for user from database
        jobBl = new JobBL();
        userBl = new UserBL();
        List<String> usernameList = userBl.getUsernameList(); //get the list of job name only

        //get data from data base and populate to user selector combo box
        combo = new DefaultComboBoxModel();
        for (String unl : usernameList) {
            combo.addElement(unl);
        }
        //set the combo box to user defined combo box
        assignedToChoser.setModel(combo);
        /**
         * **************add user to combo box ends **********************
         */

        /**
         * **************add client name to combo box
         * starts**********************
         */
        List<String> clientNameList = jobBl.getClientNameList();
        combo = new DefaultComboBoxModel();
        for (String clientName : clientNameList) {
            combo.addElement(clientName);
        }
        clientNameChoser.setModel(combo);
        /**
         * **************add client name to combo box ends
         * **********************
         */

        /**
         * **************add media house name to combo box starts
         * **********************
         */
        List<String> mediaName = jobBl.getMediaHouseName();
        combo = new DefaultComboBoxModel();
        for (String mhn : mediaName) {
            combo.addElement(mhn);
        }
        mediaHouseChoser.setModel(combo);
        /**
         * **************add media house name to combo box ends
         * **********************
         */

        /**
         * **************add publication position to combo box starts
         * **********************
         */
        combo = new DefaultComboBoxModel();
        for (PrintPosition pos : PrintPosition.values()) {
            combo.addElement(pos);
        }
        positionChoser.setModel(combo);
        /**
         * **************add publication position to combo box ends
         * **********************
         */
        
        editPanel1.add(new DateAndCalender());

    }

    public JInternalFrame getFrame() {
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        clientLeftPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editPanel1 = new javax.swing.JPanel();
        btnSaveJob = new javax.swing.JButton();
        jobId = new javax.swing.JTextField();
        designBlackAndWhite = new javax.swing.JCheckBox();
        designColor = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clientNameChoser = new javax.swing.JComboBox();
        languageNepali = new javax.swing.JCheckBox();
        languageEnglish = new javax.swing.JCheckBox();
        publicationDaysChoser = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sizeColumn = new javax.swing.JSpinner();
        sizeCm = new javax.swing.JSpinner();
        lblErrorMessage = new javax.swing.JLabel();
        mediaHouseChoser = new javax.swing.JComboBox();
        positionChoser = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jobContents = new javax.swing.JTextArea();
        assignedToChoser = new javax.swing.JComboBox();
        jobName = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jobStatusPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblJobStatus = new javax.swing.JLabel();
        markJobAsCompleted = new javax.swing.JCheckBox();

        setBorder(null);

        clientLeftPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel29.setText("Job Name");

        jLabel30.setText("Assigned To");

        jLabel32.setText("Media House Name");

        jLabel33.setText("Total Publication Day(s)");

        jLabel34.setText("Client Name");

        jLabel35.setText("Language");

        jLabel36.setText("Design Type");

        jLabel37.setText("Size");

        jLabel39.setText("Position(Newspaper / epaper)");

        jLabel5.setText("Contents");

        javax.swing.GroupLayout clientLeftPanel4Layout = new javax.swing.GroupLayout(clientLeftPanel4);
        clientLeftPanel4.setLayout(clientLeftPanel4Layout);
        clientLeftPanel4Layout.setHorizontalGroup(
            clientLeftPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientLeftPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientLeftPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientLeftPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientLeftPanel4Layout.setVerticalGroup(
            clientLeftPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientLeftPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addGap(28, 28, 28)
                .addComponent(jLabel33)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSaveJob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaveJob.setForeground(new java.awt.Color(51, 102, 0));
        btnSaveJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveJobActionPerformed(evt);
            }
        });

        designBlackAndWhite.setSelected(true);
        designBlackAndWhite.setText("Black and White");

        designColor.setText("Color");

        jLabel1.setText("col x");

        jLabel2.setText("cm");

        clientNameChoser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        languageNepali.setSelected(true);
        languageNepali.setText("Nepali");

        languageEnglish.setText("English");

        publicationDaysChoser.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel3.setText("Minimum day(s) 1 , Maximum day(s) 31");

        jLabel4.setText("Col (min 1 - max 8) x Cm (min 1 - max 50)");

        sizeColumn.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        sizeCm.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));

        mediaHouseChoser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        positionChoser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jobContents.setColumns(20);
        jobContents.setRows(5);
        jScrollPane2.setViewportView(jobContents);

        assignedToChoser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel38.setText("Due Date");

        javax.swing.GroupLayout editPanel1Layout = new javax.swing.GroupLayout(editPanel1);
        editPanel1.setLayout(editPanel1Layout);
        editPanel1Layout.setHorizontalGroup(
            editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnSaveJob, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(editPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editPanel1Layout.createSequentialGroup()
                        .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPanel1Layout.createSequentialGroup()
                                .addComponent(publicationDaysChoser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21))
                            .addGroup(editPanel1Layout.createSequentialGroup()
                                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientNameChoser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jobName)
                                    .addComponent(assignedToChoser, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mediaHouseChoser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(positionChoser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(editPanel1Layout.createSequentialGroup()
                                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editPanel1Layout.createSequentialGroup()
                                        .addComponent(languageNepali)
                                        .addGap(18, 18, 18)
                                        .addComponent(languageEnglish))
                                    .addGroup(editPanel1Layout.createSequentialGroup()
                                        .addComponent(sizeColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sizeCm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel4))
                                    .addGroup(editPanel1Layout.createSequentialGroup()
                                        .addComponent(designBlackAndWhite)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(designColor)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                        .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jobId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        editPanel1Layout.setVerticalGroup(
            editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignedToChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanel1Layout.createSequentialGroup()
                        .addComponent(designBlackAndWhite)
                        .addGap(11, 11, 11)
                        .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(sizeColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizeCm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)))
                    .addComponent(designColor))
                .addGap(18, 18, 18)
                .addComponent(clientNameChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mediaHouseChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageNepali)
                    .addComponent(languageEnglish))
                .addGap(18, 18, 18)
                .addComponent(positionChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(editPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publicationDaysChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnSaveJob, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientLeftPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(editPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clientLeftPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jobStatusPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jobStatusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Status");

        lblJobStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        markJobAsCompleted.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        markJobAsCompleted.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        markJobAsCompleted.setText("Mark Job as Completed");
        markJobAsCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markJobAsCompletedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jobStatusPanelLayout = new javax.swing.GroupLayout(jobStatusPanel);
        jobStatusPanel.setLayout(jobStatusPanelLayout);
        jobStatusPanelLayout.setHorizontalGroup(
            jobStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jobStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jobStatusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblJobStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(markJobAsCompleted, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE))
                .addContainerGap())
        );
        jobStatusPanelLayout.setVerticalGroup(
            jobStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jobStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblJobStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(markJobAsCompleted)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jobStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jobStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveJobActionPerformed
        this.buttonText = btnSaveJob.getText();
        System.out.println("btn text " + buttonText);
        if (btnSaveJob.getText().equals("Save")) {
            if (verifyDate()) {
                job = new JobBean(0, jobName.getText().trim(), assignedToChoser.getSelectedItem().toString(), designBlackAndWhite.isSelected(), designColor.isSelected(), String.valueOf(sizeColumn.getValue()), String.valueOf(sizeCm.getValue()), "", clientNameChoser.getSelectedItem().toString(), mediaHouseChoser.getSelectedItem().toString(), languageNepali.isSelected(), languageEnglish.isSelected(), positionChoser.getSelectedItem().toString(), (int) publicationDaysChoser.getValue(), jobContents.getText());
                job.setDueDate(DateAndCalender.setDueDate.toString());
                job.setUserId(UserBL.userId);
                //reset date
                DateAndCalender.setDueDate = new Date();
                JobBL.getButtonText(buttonText);
                jobBl.passJobObject(job);
//                return;
            }
        } else if (markJobAsCompleted.isSelected() && btnSaveJob.getText().equals("Update")) {
            if (verifyDate()) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to mark this job as completed?", "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    //update the database
                    System.out.println("markJobAsCompleted.isSelected() " + markJobAsCompleted.isSelected());
                    job.setJobCompleted(markJobAsCompleted.isSelected());
                    job.setJobId(Integer.parseInt(jobId.getText()));
                    job.setDueDate(DateAndCalender.setDueDate.toString());
                    //reset date
                    DateAndCalender.setDueDate = new Date();
                    //close 
                    if (new JobBL().markJobAsCompleted(job)) {
                        disableMarkAsCompleted();
                    }
                }
            }
//            return;
        } else {
            if (verifyDate()) {
                JobBL.getButtonText(buttonText);
                DateAndCalender.setDueDate = new Date();
                job = new JobBean(Integer.parseInt(jobId.getText()), jobName.getText().trim(), assignedToChoser.getSelectedItem().toString(), designBlackAndWhite.isSelected(), designColor.isSelected(), String.valueOf(sizeColumn.getValue()), String.valueOf(sizeCm.getValue()), "", clientNameChoser.getSelectedItem().toString(), mediaHouseChoser.getSelectedItem().toString(), languageNepali.isSelected(), languageEnglish.isSelected(), positionChoser.getSelectedItem().toString(), (int) publicationDaysChoser.getValue(), jobContents.getText());
                job.setJobCompleted(markJobAsCompleted.isSelected());
                job.setDueDate(DateAndCalender.setDueDate.toString());
                jobBl.passJobObject(job);
                //reset date
            }
        }
    }//GEN-LAST:event_btnSaveJobActionPerformed

    private void markJobAsCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markJobAsCompletedActionPerformed
        //disable all the fields when user clicks mark as completed
        if (markJobAsCompleted.isSelected()) {
            disableAllFields();
        } else {
            enableAllFields();
        }
    }//GEN-LAST:event_markJobAsCompletedActionPerformed

    void setButtonText(String buttonText) {
        btnSaveJob.setText(buttonText);
    }

    void setValuesToEdit(JobBean jb) {
        EditJob.jobIdToDelete = jb.getJobId();
        //populate the edit job with existing values, if we don't do this, edit form will be populated with default values
        jobId.setText(String.valueOf(jb.getJobId()));
        jobName.setText(String.valueOf(jb.getJobName()));
        assignedToChoser.setSelectedItem(jb.getAssigneeName());
        designBlackAndWhite.setSelected(jb.isDesignTypeBlackAndWhite());
        designColor.setSelected(jb.isDesignTypeColor());
        sizeColumn.setValue(Integer.parseInt(jb.getSizeColumn()));
        sizeCm.setValue(Integer.parseInt(jb.getSizeCm()));
//        jobDueDate.setText(jb.getDueDate());
        clientNameChoser.setSelectedItem(jb.getClientName());
        mediaHouseChoser.setSelectedItem(jb.getMediaHouseName());
        languageNepali.setSelected(jb.isLanguageNepali());
        languageEnglish.setSelected(jb.isLanguageEnglish());
        positionChoser.setSelectedItem(jb.getPosition());
        publicationDaysChoser.setValue(jb.getPublicationDays());
        jobContents.setText(jb.getJobContents());
        this.job = jb;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox assignedToChoser;
    private javax.swing.JButton btnSaveJob;
    private javax.swing.JPanel clientLeftPanel4;
    private javax.swing.JComboBox clientNameChoser;
    private javax.swing.JCheckBox designBlackAndWhite;
    private javax.swing.JCheckBox designColor;
    private javax.swing.JPanel editPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jobContents;
    private javax.swing.JTextField jobId;
    private javax.swing.JTextField jobName;
    public static javax.swing.JPanel jobStatusPanel;
    private javax.swing.JCheckBox languageEnglish;
    private javax.swing.JCheckBox languageNepali;
    public static javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblJobStatus;
    public static javax.swing.JCheckBox markJobAsCompleted;
    private javax.swing.JComboBox mediaHouseChoser;
    private javax.swing.JComboBox positionChoser;
    private javax.swing.JSpinner publicationDaysChoser;
    private javax.swing.JSpinner sizeCm;
    private javax.swing.JSpinner sizeColumn;
    // End of variables declaration//GEN-END:variables

    void disableAllFields() {
        jobName.setEditable(false);
        assignedToChoser.setEnabled(false);
        designBlackAndWhite.setEnabled(false);
        designColor.setEnabled(false);
        sizeColumn.setEnabled(false);
        sizeCm.setEnabled(false);
//        jobDueDate.setEnabled(false);
        clientNameChoser.setEnabled(false);
        mediaHouseChoser.setEnabled(false);
        languageNepali.setEnabled(false);
        languageEnglish.setEnabled(false);
        positionChoser.setEnabled(false);
        publicationDaysChoser.setEnabled(false);
        jobContents.setEnabled(false);
        EditJob.btnDeleteJob.setEnabled(false);

        if (ViewJob.jobCompleted.equals("Completed")) {
            disableMarkAsCompleted();
        }
    }

    private void disableMarkAsCompleted() {
        markJobAsCompleted.setEnabled(false);
        lblJobStatus.setText(ErrorMessages.JOB_MARKED_AS_COMPLETED);
        lblJobStatus.setForeground(Color.GREEN);
        btnSaveJob.setEnabled(false);

    }

    void enableAllFields() {
        jobName.setEditable(true);
        assignedToChoser.setEnabled(true);
        designBlackAndWhite.setEnabled(true);
        designColor.setEnabled(true);
        sizeColumn.setEnabled(true);
        sizeCm.setEnabled(true);
//        jobDueDate.setEnabled(true);
        clientNameChoser.setEnabled(true);
        mediaHouseChoser.setEnabled(true);
        languageNepali.setEnabled(true);
        languageEnglish.setEnabled(true);
        positionChoser.setEnabled(true);
        publicationDaysChoser.setEnabled(true);
        jobContents.setEnabled(true);
        EditJob.btnDeleteJob.setEnabled(true);
        EnableMarkAsCompleted();
    }

    private void EnableMarkAsCompleted() {
        markJobAsCompleted.setEnabled(true);
        btnSaveJob.setEnabled(true);
    }

    private boolean verifyDate() {
        if (DateAndCalender.setDueDate.before(new Date())) {
            DateAndCalender.showDialog();
            return false;
        }
        return true;
    }
    
    public void addErrorPanel(){
        System.out.println("adding error panel");
        editPanel1.add(new ErrorPanel());
    }
    
    public void setErrorMessageAndColor(String message, String color){
        ErrorPanel ep=new ErrorPanel();
//need to modify this part        
        editPanel1.add(ep);
    }
}
