/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.budthapa.jts.view.clients;

import com.budthapa.jts.business.ClientBL;
import com.budthapa.jts.model.ClientBean;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author budthapa
 */
public class ViewClient extends javax.swing.JInternalFrame {

    private ClientBL client;
    private ClientBean clientBean;
    public static DefaultTableModel table;

    /**
     * Creates new form ViewClient
     */
    public ViewClient() {
        initComponents();
        setVisible(true);
        client = new ClientBL();
        clientBean = new ClientBean();
        //bring table data from client
        initialiseTableAndFillWithData();
        
        //set ViewClient is already opened flag
        client.isViewClientClassOpen=true;
    }

    public void refreshTable(){
        initialiseTableAndFillWithData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewClientsTable = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("View list of Clients");

        viewClientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewClientsTable.setToolTipText("Double Click to Edit or Delete this row.");
        viewClientsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewClientsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(viewClientsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialiseTableAndFillWithData() {
        //initialise table and set editable to false
        table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };

        List<ClientBean> clientList = client.getClientList();
        //column name is compulsary, if not added, added rows will not be displayed
        table.addColumn("S.No");
        table.addColumn("Client Name");
        table.addColumn("Client Type");
        table.addColumn("Client Email");
        table.addColumn("Client Contact Person");
        table.addColumn("Client Contact Number");
        table.addColumn("Client Fax");
        table.addColumn("Client Address");

        for (ClientBean clientList1 : clientList) {
            //create dynamic row
            Object[] rowData = {clientList1.getClientId(), clientList1.getClientName(), clientList1.getClientType(), 
                clientList1.getClientEmail(), clientList1.getClientContactPerson(), clientList1.getClientContactNumber(), 
                clientList1.getClientFaxNumber(), clientList1.getClientAddress()};
            table.addRow(rowData);
        }
        viewClientsTable.setModel(table);

    }

    private void viewClientsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewClientsTableMouseClicked

        int id;
        String name;
        String type;
        String email;
        String contactPerson;
        String contactNumber;
        String fax;
        String address;

        //if user click twice in a row
        if (evt.getClickCount() == 2) {
            JTable table = (JTable) evt.getSource();
            int selectedRow = table.getSelectedRow();

            //get the items from the row starting from column index 0 to column max size;
            int counter=0;
            id = (int) table.getValueAt(selectedRow, counter);
            name = (String) table.getValueAt(selectedRow, ++counter);
            type = (String) table.getValueAt(selectedRow, ++counter);
            email = (String) table.getValueAt(selectedRow, ++counter);
            contactPerson = (String) table.getValueAt(selectedRow, ++counter);
            contactNumber = (String) table.getValueAt(selectedRow, ++counter);
            fax = (String) table.getValueAt(selectedRow, ++counter);
            address = (String) table.getValueAt(selectedRow, ++counter);

            //populate the add new client with these new values
            ClientBean cb = new ClientBean(id, name, type, email, contactPerson, contactNumber, fax, address);

            //open dialog to edit or delete the user;
            EditClient editClient = new EditClient();
            ClientFrame frame = new ClientFrame();
            frame.getFrame();
            frame.setVisible(true);
            editClient.add(frame);

            //set button text dynamically
            //set button text to 'update' while accessing from this class
            String buttonText = "Update";
            frame.setButtonText(buttonText);

            frame.setValuesToEdit(cb);

            editClient.rowIdToDelete = selectedRow;
        }
    }//GEN-LAST:event_viewClientsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable viewClientsTable;
    // End of variables declaration//GEN-END:variables

}
